### ISSUE TITLE
Assemble should not fail if page does not contain '#wordcount'

### ISSUE THREAD

**Issue by quartzmo** [assemble/grunt-assemble-wordcount#1]
I do not want to use wordcount in all of my layouts, nor do I want to have to write assemble targets just to scope the wordcount configuration. Can it just skip pages that do not contain the 'wordcount' id? Currently I get this error:

Assembling .tmp/index.html Assembling .tmp/index.html  ERROR
Warning: Cannot call method 'replace' of null 

I'm guessing this is from index.js:15

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
