### ISSUE TITLE
Moving to `grunt-assemble-wordcount`

### ISSUE THREAD

**Issue by doowb** [assemble/grunt-assemble-wordcount#5]
I'll be moving the `grunt-assemble` version of this code to `grunt-assemble-wordcount` and deprecating `assemble-middleware-wordcount` on npm. If anyone has any issues/questions/comments, please leave them here so we may discuss.

**Comment by jonschlinkert** [comment]
:+1: I'm good with it!

**Comment by doowb** [comment]
Done.

- [x] tagged code snapshot before moving to `grunt-assemble-wordcount`
- [x] reverted code to `grunt-assemble` (kept updates)
- [x] published `grunt-assemble-wordcount`
- [x] renamed repository to `grunt-assemble-wordcount`
